### ISSUE TITLE
收藏夹插件在没有选中收藏夹时，单首歌结束后自动停止播放，无法播放列表的前一首歌或后一首歌

### ISSUE THREAD

**Issue by Harmskyblue** [MATRIX-feather/LLin#7]
https://github.com/user-attachments/assets/98824c49-7f56-4f64-ac36-aad0618600a5

**Comment by MATRIX-feather** [comment]
点两下设置里的音乐控制插件切换回“osu!”再试试。如果没有选中任何收藏夹的话收藏夹插件不会进行歌曲切换

**Comment by Harmskyblue** [comment]
![image](https://github.com/user-attachments/assets/93f8ae1b-f973-42cd-8d9c-5a2e11a2a075)
解决了，感谢
